### ISSUE TITLE
Link not clickable when there is a space

### ISSUE THREAD

**Issue by KrauseFx** [orta/gh_inspector#10]
```
and 71 more at: https://github.com/fastlane/fastlane/search?q=Exit Status 65&type=Issues&utf8=✓
```

The `q` parameter should be encoded properly 👍

**Comment by orta** [comment]
Only when presenting it there - we should do it in the inspector, but you'll need to od it in the fastlane UI delegate

**Comment by orta** [comment]
Nah this is GHI's fault
