### ISSUE TITLE
Spelling error: inspector_successfully_recieved_report

### ISSUE THREAD

**Issue by getaaron** [orta/gh_inspector#19]
```diff
-inspector_successfully_recieved_report
+inspector_successfully_received_report
```

I think if we fix this we need to either bump the major version number or support and deprecate the old spelling

**Comment by orta** [comment]
Yeah, could support both? It's not exactly an active repo - so I'm not worried about needing to make a major server bump

**Comment by KrauseFx** [comment]
yeah we received a PR in the fastlane main repo, supporting both sounds 💯
