### ISSUE TITLE
Gem Archive Permissions

### ISSUE THREAD

**Issue by sttz** [orta/gh_inspector#9]
The latest Fastlane update was failing to load the `gh_inspector` gem on OS X El Capitan and after some digging the issue turned out to be that all the gem's files were readable only by their owner (which is root on OS X). Giving read permission to everyone fixed the load issue for me.

Looking at the gem file, the permissions seem to be coming from there:

    $ tar -vtf data.tar.gz
    -rw-------  0 wheel  wheel      94 Jun 20 20:00 .gitignore
    -rw-------  0 wheel  wheel      31 Jun 20 20:00 .rspec
    -rw-------  0 wheel  wheel    2112 Jun 20 20:00 .rubocop.yml
    -rw-------  0 wheel  wheel      76 Jun 20 20:00 .travis.yml
    -rw-------  0 wheel  wheel     104 Jun 20 20:00 Gemfile
    -rw-------  0 wheel  wheel    3536 Jun 20 20:00 README.md
    -rw-------  0 wheel  wheel    1435 Jun 20 20:00 Rakefile
    -rwx------  0 wheel  wheel     246 Jun 20 20:00 bin/console
    -rwx------  0 wheel  wheel     131 Jun 20 20:00 bin/setup
    -rw-------  0 wheel  wheel     983 Jun 20 20:00 gh_inspector.gemspec
    -rw-------  0 wheel  wheel     191 Jun 20 20:00 lib/gh_inspector.rb
    -rw-------  0 wheel  wheel    3351 Jun 20 20:00 lib/gh_inspector/evidence.rb
    -rw-------  0 wheel  wheel     843 Jun 20 20:00 lib/gh_inspector/exception_hound.rb
    -rw-------  0 wheel  wheel    2343 Jun 20 20:00 lib/gh_inspector/inspector.rb
    -rw-------  0 wheel  wheel    3079 Jun 20 20:00 lib/gh_inspector/sidekick.rb
    -rw-------  0 wheel  wheel      50 Jun 20 20:00 lib/gh_inspector/version.rb

**Comment by orta** [comment]
doh

**Comment by orta** [comment]
I had this issue on another gem too

**Comment by orta** [comment]
https://github.com/danger/danger/issues/260 here it is

**Comment by orta** [comment]
![screen shot 2016-06-22 at 2 24 13 pm](https://cloud.githubusercontent.com/assets/49038/16278439/00f2a38c-3885-11e6-98f7-3d6a1f772b29.png)

released 1.0.1 with a fix, if Fastlane is using a fuzzy dependency this should fix it 👍 

As you have 1.0, you can do `gem install gh_inspector` to update your version
